language: python
python: "2.7_with_system_site_packages"
sudo: false
script:
    - make install
    - make test
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
            - texlive-latex-recommended
            - texlive-font-utils
