language: python
python: "2.7"
sudo: false
script: make
addons:
    apt:
        packages:
            - fontforge-nox
            - python-fontforge
            - texlive-latex-recommended
            - texlive-font-utils
